### PR TITLE
Added files needed to run tests on appveyor.

### PR DESCRIPTION
**Pull request by moorepants**
Addresses #303.
- [ ] There are no merge conflicts.
- [ ] If there is a related issue, a reference to that issue is in the
  commit message.
- [ ] Unit tests have been added for the new feature.
- [ ] The PR passes tests both locally (run `nosetests`) and on Travis CI.
- [ ] All public methods and classes have docstrings. (We use the [numpydoc
  format](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).)
- [ ] An explanation has been added to the online documentation. (`docs`
  directory)
- [ ] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [ ] The new feature is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [ ] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [ ] All reviewer comments have been addressed.
- [x] Merge #313 and update this branch wrt to master.
- [x] Figure out why the temp files from Cython are not accessible.
- [x] Skip Theano tests.
- [x] Figure out why compilation fails with Python 3.4

### CODE REVIEW

**Comment by moorepants** [comment]
This is the Python 3.4 compilation error:

```
[1/1] Cythonizing pydy_codegen_0.pyx
running build_ext
building 'pydy_codegen_0' extension
creating build
creating build\temp.win-amd64-3.5
creating build\temp.win-amd64-3.5\Release
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Python34_64\lib\site-packages\numpy\core\include -IC:\Python34_64\include -IC:\Python34_64\include "-Ic:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE" "-IC:\Program Files\Microsoft SDKs\Windows\v7.1\INCLUDE" "-IC:\Program Files\Microsoft SDKs\Windows\v7.1\INCLUDE\gl" /Tcpydy_codegen_0.c /Fobuild\temp.win-amd64-3.5\Release\pydy_codegen_0.obj
pydy_codegen_0.c
c:\python34_64\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION 
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Python34_64\lib\site-packages\numpy\core\include -IC:\Python34_64\include -IC:\Python34_64\include "-Ic:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE" "-IC:\Program Files\Microsoft SDKs\Windows\v7.1\INCLUDE" "-IC:\Program Files\Microsoft SDKs\Windows\v7.1\INCLUDE\gl" /Tcpydy_codegen_0_c.c /Fobuild\temp.win-amd64-3.5\Release\pydy_codegen_0_c.obj
pydy_codegen_0_c.c
creating C:\Users\appveyor\AppData\Local\Temp\1\tmphl0sjk_x.pydy_compile\build\lib.win-amd64-3.5
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Python34_64\libs /LIBPATH:C:\Python34_64\PCbuild\amd64 "/LIBPATH:c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Lib\amd64" "/LIBPATH:C:\Program Files\Microsoft SDKs\Windows\v7.1\Lib\X64" /EXPORT:PyInit_pydy_codegen_0 build\temp.win-amd64-3.5\Release\pydy_codegen_0.obj build\temp.win-amd64-3.5\Release\pydy_codegen_0_c.obj /OUT:build\lib.win-amd64-3.5\pydy_codegen_0.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\pydy_codegen_0.cp35-win_amd64.lib
LINK : fatal error LNK1117: syntax error in option 'MANIFEST:EMBED,ID=2'
error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1117
```

**Comment by moorepants** [comment]
Here are some findings:

The appveyor Python demo had a similar failure at some point:
https://ci.appveyor.com/project/ogrisel/python-appveyor-demo/build/1.0.152

Same error and conclusion that the correct compiler was not installed:
https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/cTz7cVPQkKM/-XlEAFIuAgAJ

Build is incorrectly using the 2008 compiler:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/966cf58b-ee8b-4333-810d-dd81ff7f0b3d/getting-manifest-error-in-dll-project-upgraded-to-vs2012-from-vs2008?forum=vcgeneral

astropy/photutils same error:
https://ci.appveyor.com/project/Astropy/photutils/build/1.0.154/job/vt999t9pemy8dcqq

**Comment by moorepants** [comment]
@chrisdembia Do you have any idea about this? I know you've worked with appveyor more.

**Comment by moorepants** [comment]
The compilation was failing due to a mismatch in the installed miniconda python version (i.e. Miniconda35 was being downloaded when I thought it was Miniconda3.4).

**Comment by moorepants** [comment]
@pydy/pydy-developers Ok, this is finally working on appveyor for Python 2.7, 3.4, and 3.5. Needs review.

**Comment by moorepants** [comment]
@pydy/pydy-developers I squashed commits here and this is ready for review.

**Comment by moorepants** [comment]
@yashu-seth Would you like to review this PR? If so, please look through the list at the top of the PR and confirm that I've covered the relevant points.

**Comment by yashu-seth** [comment]
@moorepants okay let me see this.

**Comment by chrisdembia** [comment]
Appveyor badge doesn't show? 
image

**Comment by moorepants** [comment]
I think it will show once the appveyor.yml file is in the master branch.

**Comment by yashu-seth** [comment]
@moorepants I think everything has been covered.

**Comment by moorepants** [comment]
@chrisdembia I'm going to merge based on @yashu-seth's review unless you have further comments. I'll fix the appveyor badge if it doesn't show up after merging.

**Comment by chrisdembia** [comment]
Sounds good.

**Pull request merged**
