### PR TITLE
Added proper imports to the sliding ladder example.

### PR DESCRIPTION
**Pull request by moorepants**
Fixes issue #214.

- Changed the README to an rst file.
- Added isntructions to run the example to the README.
- Added proper imports to the Python file.
- Updated the text in the Python file and some variable names.

- [x] There are no merge conflicts.
- [x] A figure (preferrably SVG) has been added for the example.
- [x] The required versions of all dependencie have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
- [ ] A `run.py` file that executes the example is included.
- [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
@pydy/pydy-developers This needs a review. Thanks.

**Comment by sahilshekhawat** [comment]
Good to go in, not sure how it work working before without the imports.

**Comment by moorepants** [comment]
It didn't work with out the imports.

**Comment by moorepants** [comment]
Merging without the `run.py` file because we haven't actually figured out how to support that yet.

**Pull request merged**
