### PR TITLE
Update to the npendulum example

### PR DESCRIPTION
**Pull request by moorepants**
Fixes issue #216.

- Removed the "bloggy" style text.
- Specified the dependencies.
- Included specific dependencies at the end of the notebook.
- Removed the ogv output, as Firefox now supports mp4 and matplotlib seems to fail on ogg: matplotlib/matplotlib#2764
- avconv is required as the writer.
- Updated to IPython notebook v4 (IPython 3.0)
- Changed to the linearizer introduced in SymPy 0.7.6.

Tasks:
- [x] Add the correct channel for the control and slycot packages.
- [x] There are no merge conflicts.
- [x] A figure (preferrably SVG) has been added for the example.
- [x] The required versions of all dependencie have been noted. (For notebooks, the [version information extension](https://github.com/jrjohansson/version_information) is helpful for this.)
- [ ] A `run.py` file that executes the example is included.
- [x] All reviewer comments have been addressed.
- [x] Figure out why the controllability test is failing.

### CODE REVIEW

**Comment by moorepants** [comment]
@pydy/pydy-developers This needs a review. I have one issue too. I am not sure why I'm getting a bad controllability matrix.

**Comment by sahilshekhawat** [comment]
I am getting error while creating animation i.e. while running 
```
animate_pendulum(t, y, arm_length, filename="open-loop.ogv")
animate_pendulum(t, y, arm_length, filename="open-loop.mp4")
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-90a43d6b2379> in <module>()
      1 animate_pendulum(t, y, arm_length, filename="open-loop.ogv")
----> 2 animate_pendulum(t, y, arm_length, filename="open-loop.mp4")

<ipython-input-19-f9388e5bb42b> in animate_pendulum(t, states, length, filename)
     74     # save the animation if a filename is given
     75     if filename is not None:
---> 76         anim.save(filename, fps=30, codec='libx264')

/home/sahil/anaconda/envs/pydy-dev/lib/python2.7/site-packages/matplotlib/animation.pyc in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
    765                     # TODO: Need to see if turning off blit is really necessary
    766                     anim._draw_next_frame(d, blit=False)
--> 767                 writer.grab_frame(**savefig_kwargs)
    768 
    769         # Reconnect signal for first draw if necessary

/home/sahil/anaconda/envs/pydy-dev/lib/python2.7/contextlib.pyc in __exit__(self, type, value, traceback)
     22         if type is None:
     23             try:
---> 24                 self.gen.next()
     25             except StopIteration:
     26                 return

/home/sahil/anaconda/envs/pydy-dev/lib/python2.7/site-packages/matplotlib/animation.pyc in saving(self, *args)
    186         self.setup(*args)
    187         yield
--> 188         self.finish()
    189 
    190     def _run(self):

/home/sahil/anaconda/envs/pydy-dev/lib/python2.7/site-packages/matplotlib/animation.pyc in finish(self)
    376             raise RuntimeError('Error creating movie, return code: '
    377                                + str(self._proc.returncode)
--> 378                                + ' Try running with --verbose-debug')
    379 
    380     def cleanup(self):

RuntimeError: Error creating movie, return code: 1 Try running with --verbose-debug
```

**Comment by moorepants** [comment]
Are you running this branch? I removed the `ogv` call that caused this error.

**Comment by sahilshekhawat** [comment]
Yeah, i forgot to checkout. But there is another error at ``sm.trigsimp(kane.mass_matrix)`` 
``ValueError Expected "\right" (at char 6), (line:1, col:7)``

**Comment by moorepants** [comment]
I think that is because you don't have latex installed. Are you using SymPy 0.7.6? I think that may come from matplotlib not supporting the `\right[` latex symbol. This may be fixed in sympy master.

**Comment by moorepants** [comment]
You can use `init_vprinting(mathjax=True)` or something like that. I forget the kwarg.

**Comment by sahilshekhawat** [comment]
It works but I have no idea what controability is. So, can't comment on that. Apart from that, The example is working.

**Comment by moorepants** [comment]
Ok, thanks. I'll ask some others about the controllability issue. I'm guessing it is an numeric issue.

**Comment by moorepants** [comment]
I've updated the example with an explanation of why the rank computation of the controllability matrix does not work for n=5 as it is ill conditioned. I'm not sure why it worked in the previous incarnation of this notebook. 

So this is good to merge. Please have a final look at it, check off the checklist, and merge. Thanks.

**Comment by sahilshekhawat** [comment]
Thanks for the explanation, Every thing's working now.

**Comment by sahilshekhawat** [comment]
Merging without the run.py file because we haven't actually figured out how to support that yet.

**Pull request merged**
