### PR TITLE
Add Python 3.5 to Travis test matrix

### PR DESCRIPTION
**Pull request by oliverlee**

### CODE REVIEW

**Comment by oliverlee** [comment]
Cython 0.20 is not available for Python 3.5 in conda:

```
(dev)oliver@enif:~/repos/pydy$ conda search cython | grep py35
                             0.23.1                   py35_0  defaults        
                             0.23.2                   py35_0  defaults        
                             0.23.3                   py35_0  defaults        
                          *  0.23.4                   py35_0  defaults 
```

**Comment by moorepants** [comment]
I should be able to build a Cython package for 3.5 pretty quickly. Let me check.

**Comment by moorepants** [comment]
I added Cython 0.20.2 for Py 3.5 to our anaconda channel: https://anaconda.org/pydy/cython/files

**Comment by moorepants** [comment]
You should add this to `.travis.yml`:

`conda config --add channels pydy`

**Comment by oliverlee** [comment]
We also need the following packages built for Python 3.5:
scipy 0.14
sympy 0.7.5
ipython 0.3.0

**Comment by moorepants** [comment]
Ok, scipy might be tricky. I've failed to get that to work in the past. Maybe it is easier now. I'll give it a shot.

**Comment by oliverlee** [comment]
We'll need to first merge this: https://github.com/pydy/pydy/pull/282
as Travis will fail due to minimums not matching the binaries in pydy anaconda channel: https://anaconda.org/pydy

**Comment by moorepants** [comment]
@oliverlee I think I have all the necessary conda packages on our channel now. Can you update with master here and rerun the tests.

**Comment by oliverlee** [comment]
Can't do it within the next week, possibly longer. Feel free to submit the
patches with your account.

**Comment by moorepants** [comment]
Close in favor of #305.

**Pull request closed without merging**
