### PR TITLE
Added a conda recipe for PyDy 0.2.1 and conda build instructions.

### PR DESCRIPTION
**Pull request by moorepants**
This is preparation to fix issue #170.

- [x] There are no merge conflicts.
- [x] If there is a related issue, a reference to that issue is in the
  commit message.
- [ ] Unit tests have been added for the new feature.
- [x] The PR passes tests both locally (run `nosetests`) and on Travis CI.
- [ ] All public methods and classes have docstrings. (We use the [numpydoc
  format](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).)
- [x] An explanation has been added to the online documentation. (`docs`
  directory)
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [x] The new feature is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
The built package is available here: https://binstar.org/pydy/pydy

@pydy/pydy-developers This needs a review.

**Comment by sahilshekhawat** [comment]
``conda update conda`` is raising error
```
╰─$ conda update conda
Error: package 'conda' is not installed in /home/sahil/anaconda/envs/test
```

**Comment by sahilshekhawat** [comment]
Oh! sorry, that was very basic error.

**Comment by sahilshekhawat** [comment]
:+1:

**Comment by moorepants** [comment]
Please check off all the boxes that are relevant as a reviewer. Let's get in the habit of that.

**Comment by moorepants** [comment]
And you can merge when you are happy with the code.

**Comment by sahilshekhawat** [comment]
I have, I don't think any more checkboxes are relevant

**Comment by moorepants** [comment]
Ok, you can merge.

**Pull request merged**
