### PR TITLE
Updated System to work with the new generate_ode_function().

### PR DESCRIPTION
**Pull request by moorepants**
Fixes issue #116.

- [x] There are no merge conflicts.
- [x] If there is a related issue, a reference to that issue is in the
  commit message.
- [x] Unit tests have been added for the bug. (Please reference the issue #
  in the unit test.)
- [x] The tests pass both locally (run `nosetests`) and on Travis CI.
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [x] The bug fix is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
Oddly Travis tests pass even though this error fires:
```
pydy.viz.tests.test_scene.test_create_static_html ... Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
Traceback (most recent call last):
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 523, in rhs
    xdot = self._base_rhs(q, u, *args[2:])
  File "/home/travis/build/pydy/pydy/pydy/codegen/ode_function_generators.py", line 690, in base_rhs
    M, F = self.eval_arrays(*args)
TypeError: <lambda>() takes exactly 3 arguments (4 given)
odepack.error: Error occured while calling the Python function named rhs
ok
```

**Comment by moorepants** [comment]
Ok, this should be working now. Can someone please review?

@pydy/pydy-developers @sahilshekhawat

**Comment by moorepants** [comment]
@pydy/pydy-developers Can someone please review this PR?

**Comment by moorepants** [comment]
@pydy/pydy-developers This has been sitting for a week now with no review. It'd be great if someone can take 5 minutes and look it over.

**Comment by sahilshekhawat** [comment]
Related issue is not referenced in any of the commit's message but we can close it ourselves. Also, do we have to document every PR in Release Notes?

**Comment by moorepants** [comment]
We don't have to document every PR in the release notes. We should only document changes from release to release. So if you introduce a bug in master and then fix it before release, there is no reason to have that in the release notes. This specific thing doesn't need to be in the release notes, it is already covered when we mention the generator overhaul.

**Comment by sahilshekhawat** [comment]
Okay. I think its good to go in. +1

**Comment by moorepants** [comment]
Thanks @sahilshekhawat. I'll merge.

**Pull request merged**
