### PR TITLE
Planes now render both sides.

### PR DESCRIPTION
**Pull request by moorepants**
- [x] There are no merge conflicts.
- [ ] If there is a related issue, a reference to that issue is in the
  commit message.
- [ ] Unit tests have been added for the bug. (Please reference the issue #
  in the unit test.)
- [x] The tests pass both locally (run `nosetests`) and on Travis CI.
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [ ] The bug fix is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
@pydy/pydy-developers This needs a quick review.

**Comment by tarzzz** [comment]
:+1: awesome!!

**Comment by moorepants** [comment]
Thanks Tarun. Please check off the relevant items in the check list and let me know if this i ready to merge.

**Comment by moorepants** [comment]
Thanks, will update release notes separately.

**Pull request merged**
