### PR TITLE
Fixes bug mentioned in issue #256

### PR DESCRIPTION
**Pull request by yashu-seth**
- [x] There are no merge conflicts.
- [x] If there is a related issue, a reference to that issue is in the
  commit message.
- [x] Unit tests have been added for the bug. (Please reference the issue #
  in the unit test.)
- [x] The tests pass both locally (run `nosetests`) and on Travis CI.
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [ ] The bug fix is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by yashu-seth** [comment]
@moorepants I think there should be tests for ```_generate_rhs_docstring``` function as well.

**Comment by moorepants** [comment]
Yes, ideally we'd have a test for this. Would you like to add it? The tests will be a bit verbose but that is fine I suppose.

**Comment by yashu-seth** [comment]
Okay. I'll add them.

**Comment by yashu-seth** [comment]
i'll fix the pep8 issues after adding the remaining tests.

**Comment by yashu-seth** [comment]
@moorepants Please have a look at this.

**Comment by moorepants** [comment]
Looks good.

**Pull request merged**
