### PR TITLE
Added OctaveMatrixGenerator.

### LINKED ISSUE #134: Create Generator class for Octave and Matlab
SymPy now has Octave/Matlab code printing and generators. We should support printing and wrapping Octave/Matlab code. The Octave one can be wrapped with oct2py and Matlab now has some facilities to interact with Python, so maybe even that could be wrapped.

### PR DESCRIPTION
**Pull request by moorepants**
Fixes #134.

- Introduces an abstract base class for MatrixGenerators.
- Adds a simple subclass for generating Octave code from SymPy matrices.

Merge Checklist

- [ ] There are no merge conflicts.
- [ ] If there is a related issue, a reference to that issue is in the
  commit message.
- [ ] Unit tests have been added for the new feature.
- [ ] The PR passes tests both locally (run `nosetests`) and on Travis CI.
- [ ] All public methods and classes have docstrings. (We use the [numpydoc
  format](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).)
- [ ] An explanation has been added to the online documentation. (`docs`
  directory)
- [ ] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [ ] The new feature is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [ ] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [ ] All reviewer comments have been addressed.

TODO:

- [x] Get the function inputs and outputs to work correctly.
- [x] Add a write method to dumping to file.
- [x] Get feedback on organization.
- [x] Make CMatrixGenerator to subclass MatrixGenerator.
- [x] Add prose docs.
- [x] Raise an error if a too old version of SymPy is installed. The octave printer may only be in 0.7.6+.

### CODE REVIEW

**Comment by moorepants** [comment]
@pydy/pydy-developers @yashu-seth 

This PR is ready for review. It introduces an OctaveMatrixGenerator similar to the CMatrixGenerator. I need some feedback on how to organize the classes and files. Right now we have:

Superclass: pydy.codegen.matrix_generators.MatrixGenerator
Subclass: pydy.codegen.matrix_generators.OctaveMatrixGenerator
Stand alone class: pydy.codegen.c_code.CMatrixGenerator

I'd like both CMatrixGenerator and OctaveMatrixGenerator to subclass MatrixGenerator eventually, but how should I organize the files? All in `matrix_generators.py` or each one in it's own, e.g. `c_code.CMatrixGenerator`, `octave_code.OctaveMatrixGenerator`. The later is similar to the organization of the SymPy printers but the subclasses here are pretty lightweight.

**Comment by yashu-seth** [comment]
@moorepants I am in favor of keeping separate files. I also feel that the subclasses of ```ODEFunctionGenerator``` should also be separated. When I viewed the code for the first time things would have been a lot clearer had it been the case.

**Comment by moorepants** [comment]
This is ready for a final review.

**Comment by moorepants** [comment]
@pydy/pydy-developers This should be relatively easy to review. Nothing crazy different than what's there. If someone can give me a +1 I could merge.

**Pull request merged**
