### PR TITLE
Added Pull request template from contributing

### LINKED ISSUE #329: Move our contributing checklist to an issue template
Github just introduced this new feature:

https://github.com/blog/2111-issue-and-pull-request-templates

### PR DESCRIPTION
**Pull request by sahilshekhawat**
Fixes #329 
- [ ] There are no merge conflicts.
- [ ] If there is a related issue, a reference to that issue is in the
   commit message.
- [ ] Unit tests have been added for the new feature.
- [ ] The PR passes tests both locally (run `nosetests`) and on Travis CI.
- [ ] All public methods and classes have docstrings. (We use the [numpydoc
   format](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).)
- [ ] An explanation has been added to the online documentation. (`docs`
   directory)
- [ ] The code follows PEP8 guidelines. (use a linter, e.g.
   [pylint](http://www.pylint.org), to check your code)
- [ ] The new feature is documented in the [Release
   Notes](https://github.com/pydy/pydy#release-notes).
- [ ] The code is backwards compatible. (All public methods/classes must
   follow deprecation cycles.)
- [ ] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
I guess this is fine. The user can then delete the irrelevant checklists when they edit the github message.

**Comment by moorepants** [comment]
Is it possible to put this in a `.github` folder?

**Comment by sahilshekhawat** [comment]
yes, we can shift ``contributing.md``, ``pull_request_template.md`` and ``issue_template.md`` (when we have one) to ``.github/``.

Should we create an issue_template too?

**Comment by moorepants** [comment]
I like the CONTRIBUTING file on the top level. It isn't specific to github. What would you put in an issue template? We don't have any customs for issues at the moment that I can think of. I think we can use the pull request template because we do have a method that works with github's system. But you need to remove the checklists from the CONTRIBUTING file if you are making this template.

**Comment by sahilshekhawat** [comment]
Sure.

**Pull request merged**
