### PR TITLE
Test optional dependencies only if installed

### PR DESCRIPTION
**Pull request by oliverlee**
This commit resolves issue https://github.com/pydy/pydy/issues/52.

### CODE REVIEW

**Comment by oliverlee** [comment]
```
(dev)oliver@enif:~/repos/pydy$ nosetests -v pydy/codegen/tests/test_code.py:TestCode.test_generate_ode_function
/home/oliver/repos/pydy/pydy/codegen/code.py:25: PyDyDeprecationWarning: This module, 'pydy.codgen.code', is deprecated. The function 'generate_ode_function' can be found in the 'pydy.codegen.ode_function_generator' module. 'CythonGenerator' has been removed, use 'pydy.codegen.cython_code.CythonMatrixGenerator' instead.
  PyDyDeprecationWarning)
pydy.codegen.tests.test_code.TestCode.test_generate_ode_function ... /home/oliver/repos/pydy/pydy/codegen/code.py:71: PyDyDeprecationWarning: This function is deprecated and will be removed in PyDy 0.4.0. Use the the new 'generate_ode_function' in 'pydy.codegen.ode_function_generator'
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/ode_function_generators.py:397: PyDyDeprecationWarning: The old style args, i.e. {'constants': , 'specified'}, for the generated function will be removed in PyDy 0.4.0.
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/code.py:71: PyDyDeprecationWarning: This function is deprecated and will be removed in PyDy 0.4.0. Use the the new 'generate_ode_function' in 'pydy.codegen.ode_function_generator'
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/ode_function_generators.py:397: PyDyDeprecationWarning: The old style args, i.e. {'constants': , 'specified'}, for the generated function will be removed in PyDy 0.4.0.
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/code.py:71: PyDyDeprecationWarning: This function is deprecated and will be removed in PyDy 0.4.0. Use the the new 'generate_ode_function' in 'pydy.codegen.ode_function_generator'
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/ode_function_generators.py:397: PyDyDeprecationWarning: The old style args, i.e. {'constants': , 'specified'}, for the generated function will be removed in PyDy 0.4.0.
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/code.py:71: PyDyDeprecationWarning: This function is deprecated and will be removed in PyDy 0.4.0. Use the the new 'generate_ode_function' in 'pydy.codegen.ode_function_generator'
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/ode_function_generators.py:397: PyDyDeprecationWarning: The old style args, i.e. {'constants': , 'specified'}, for the generated function will be removed in PyDy 0.4.0.
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/code.py:71: PyDyDeprecationWarning: This function is deprecated and will be removed in PyDy 0.4.0. Use the the new 'generate_ode_function' in 'pydy.codegen.ode_function_generator'
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/ode_function_generators.py:397: PyDyDeprecationWarning: The old style args, i.e. {'constants': , 'specified'}, for the generated function will be removed in PyDy 0.4.0.
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/code.py:71: PyDyDeprecationWarning: This function is deprecated and will be removed in PyDy 0.4.0. Use the the new 'generate_ode_function' in 'pydy.codegen.ode_function_generator'
  PyDyDeprecationWarning)
/home/oliver/repos/pydy/pydy/codegen/ode_function_generators.py:397: PyDyDeprecationWarning: The old style args, i.e. {'constants': , 'specified'}, for the generated function will be removed in PyDy 0.4.0.
  PyDyDeprecationWarning)
ok

----------------------------------------------------------------------
Ran 1 test in 1.602s

OK
```

```
(dev)oliver@enif:~/repos/pydy$ conda list cython
# packages in environment at /home/oliver/miniconda3/envs/dev:
#

(dev)oliver@enif:~/repos/pydy$ conda list theano
# packages in environment at /home/oliver/miniconda3/envs/dev:
#
theano                    0.7.0               np110py35_0  
```

**Comment by moorepants** [comment]
FYI, we can use sympy's tools for this too. The have a decorator for tests that is nice.

**Comment by oliverlee** [comment]
Can you point out an example?

**Comment by moorepants** [comment]
Sorry, I think it is only for doctests:

https://github.com/sympy/sympy/blob/a57f3c43b9c86979ff7fe04d520bc404b94d859a/sympy/plotting/plot.py#L208

**Pull request merged**
