### PR TITLE
Drop minimum dependency versions

### PR DESCRIPTION
**Pull request by oliverlee**

### CODE REVIEW

**Comment by oliverlee** [comment]
This needs to be merged first: https://github.com/pydy/pydy/pull/279
and binaries need to be uploaded to the pydy anaconda channel: https://anaconda.org/pydy. Refer to this issue: https://github.com/pydy/pydy/issues/271

**Comment by moorepants** [comment]
I'm working on the conda recipes we need here: https://github.com/pydy/pydy-conda-recipes

**Comment by oliverlee** [comment]
Thanks for uploading those packages. I think a few are still missing:

```
Hint: the following packages conflict with each other:
  - numpy 1.8.1*
  - theano 0.7|0.7.0*
  - python 3.3*
```

```
Hint: the following packages conflict with each other:
  - numpy 1.8.1*
  - theano 0.7|0.7.0*
  - python 3.4*
```

**Comment by moorepants** [comment]
Yes, there are still missing ones. I have recipes that can be manually tweaked to build them, but I was hoping to get them all generalized this weekend. I'll have some time this later week to get the recipes fixed and all versions built.

**Comment by oliverlee** [comment]
Thanks. I didn't know if you forgot or weren't done yet since I don't know how the conda recipes work.

**Comment by moorepants** [comment]
I can push some WIP prs to the repo with the current state.

**Comment by moorepants** [comment]
Here are the WIP PRs: https://github.com/pydy/pydy-conda-recipes/pulls

I'm slammed this week, so it won't be till later or the weekend that I finished this.

**Pull request merged**
