### PR TITLE
Update Differential Drive Example

### PR DESCRIPTION
**Pull request by jcrist**
Cleaning up example code to be more example-y. Moving non-notebook files to a notebook format. Addresses #44.

### CODE REVIEW

**Comment by moorepants** [comment]
Is this ready for review?

**Comment by moorepants** [comment]
Nevermind.

**Comment by jcrist** [comment]
Ping @moorepants : I'd like to direct people to the updated nbviewer link for this example, can we merge this?

**Comment by moorepants** [comment]
+1

**Pull request merged**
