### PR TITLE
Don't assume user enters input in server shutdown

### PR DESCRIPTION
**Pull request by oliverlee**

### CODE REVIEW

**Comment by moorepants** [comment]
+1 if the Py 2.7 test passes on the retry. Looks like the numpy install was boogered or something.

**Comment by moorepants** [comment]
This may be the Travis issue: https://github.com/conda/conda/issues/1621

**Comment by moorepants** [comment]
This is failing because of an issue from anaconda's side:

https://github.com/conda/conda/issues/444

They introduced a dependency on a new libfortran package but didn't make it backwards compatible with all NumPy versions. If we switch to NumPy 1.7.1 it should work.

**Comment by oliverlee** [comment]
@moorepants can you merge this?

**Pull request merged**
