### PR TITLE
Improvements to the camera code.

### PR DESCRIPTION
**Pull request by moorepants**
- Utilized inheritance from VisualizationFrame.
- Added more tests.
- Improved doc strings.
- Fixed getters/setters.

Review stuff:

- [x] There are no merge conflicts.
- [x] If there is a related issue, a reference to that issue is in the
  commit message.
- [x] Unit tests have been added for the bug. (Please reference the issue #
  in the unit test.)
- [x] The tests pass both locally (run `nosetests`) and on Travis CI.
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [x] The bug fix is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
@pydy/pydy-developers @yashu-seth This needs a review.

**Comment by yashu-seth** [comment]
Have the release notes been updated?

**Comment by moorepants** [comment]
This doesn't change any functionality. It is more or less a bug fix. I'll add a note though.

**Comment by moorepants** [comment]
Ok, the note has been added.

**Comment by moorepants** [comment]
@yashu-seth Any more comments here? I'd like to get this merged for the 0.3.1 release.

**Comment by yashu-seth** [comment]
Everything else seems fine to me.

**Pull request merged**
