### PR TITLE
Enhanced the chaos pendulum (baby boot) example.

### PR DESCRIPTION
**Pull request by moorepants**
- [x] There are no merge conflicts.
- [x] A figure (preferrably SVG) has been added for the example.
- [x] The required versions of all dependencies have been noted. (For
  notebooks, the [version information
  extension](https://github.com/jrjohansson/version_information) is helpful
  for this.)
- [x] A `run.py` file that executes the example is included.
- [ ] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
@pydy/pydy-developers This need a review.

@mvnnn @satyeshmundra Would you all like to review and test this example out.

**Comment by mvnnn** [comment]
thanks@moorepants, i would like to work on this issue.

**Comment by moorepants** [comment]
This isn't an issue. It is a pull request that includes code I wrote yesterday. I'd like for someone else to try the code and review this pull request. You are welcome to do that.

**Comment by oliverlee** [comment]
Are we still doing a `run.py` file?

**Comment by oliverlee** [comment]
+1

**Comment by mvnnn** [comment]
Material ```foil``` not working correctly.

**Comment by moorepants** [comment]
I added a run.py and versions I used are listed in the notebook.

**Comment by moorepants** [comment]
@mvnnn Please report that as a separate issue. I don't think it has anything to do with this example.

**Comment by oliverlee** [comment]
I'm going to merge this unless there's any reason not to @moorepants

**Comment by moorepants** [comment]
I think it is ready to go! Thanks.

**Pull request merged**
