### PR TITLE
Swapped order of nonholonomic constraints in Carvallo-Whipple example

### PR DESCRIPTION
**Pull request by moorepants**
The order of the nonholonomic constraints can affect numerical stability due to the symbolic linear solves internal to KanesMethod. This order ensures that the Basu-Mandal comparison matches to machine precision. It does not remove the divide-by-zero issues for q7=0.0.

### CODE REVIEW

**Comment by moorepants** [comment]
I'm getting this error on windows:

```
Run mamba install -q -y coverage cython matplotlib nose numpy pythreejs "sympy<1.10" scipy
  mamba install -q -y coverage cython matplotlib nose numpy pythreejs "sympy<1.10" scipy
  shell: C:\Program Files\Git\bin\bash.EXE -l {0}
  env:
    INPUT_RUN_POST: true
    CONDA: C:\Miniconda3
    CONDA_PKGS_DIR: C:\Users\runneradmin\conda_pkgs_dir
bash: line 1: 1.10: No such file or directory
Error: Process completed with exit code 1.
```

**Comment by moorepants** [comment]
Maybe this is the issue: https://scikit-learn.org/stable/install.html#troubleshooting

**Comment by moorepants** [comment]
@brocksam do you have any idea why this command is failing on Windows? I think it may be to do with the `"sympy<1.10"` part, but I'm not sure.

**Comment by moorepants** [comment]
Also @TJStienstra, as a windows user, maybe you have a clue?

**Comment by TJStienstra** [comment]
I have no clue. One thing that I do know is that you should not use sympy 1.10, due to the `Point.vel` bug.

**Comment by moorepants** [comment]
It was the `"sympy<1.10"`, `sympy=1.8` worked. Some bash parsing on windows issue.

**Pull request merged**
