### PR TITLE
Disable rerun

### PR DESCRIPTION
**Pull request by tarzzz**
Fixes issue #92.

- [x] There are no merge conflicts.
- [x] If there is a related issue, a reference to that issue is in the
  commit message.
- [ ] Unit tests have been added for the new feature.
- [ ] The PR passes tests both locally (run `nosetests`) and on Travis CI.
- [x] All public methods and classes have docstrings. (We use the [numpydoc
  format](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).)
- [x] An explanation has been added to the online documentation. (`docs`
  directory)
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [ ] The new feature is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [ ] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
@tarzzz What is this PR? Can you explain it.

**Comment by tarzzz** [comment]
This PR is to "disable" the rerun simulations button, if we are not using System. The system contains the desired attributes to support rerun. if we are not using System class, but using the Kane's or Langrange's method explicitly, the visualization should work fine on the notebook, but we cannot re-run the simulation, so we need to disable the button.

**Comment by moorepants** [comment]
Got it. There are some remaining open check boxes on the list at the top. Once those are addressed let's merge. Any way you can write a test for this?

**Comment by moorepants** [comment]
@tarzzz Are you planning to finish this up?

**Comment by tarzzz** [comment]
yes I will.
give me a day to finish it up.

**Comment by moorepants** [comment]
Ok, thanks.

**Comment by moorepants** [comment]
@tarzzz It's been two days and we haven't heard from you. If you aren't going to be able to work on any issues before the release we should unassign you from the PRs and issues that you are currently assigned to. What is your plan?

**Comment by tarzzz** [comment]
Hi Jason,

My time is totally covered up in my office work these days. I have been
staying in office for about ~12 hours these days, mostly because of the
pending work when I took the sick leave.

Might not be able to work on the issues.
Will request you to assign someone else on the same.
Sorry for the inconvenience caused.

Thanks
Tarun Gaba

**Comment by moorepants** [comment]
Thanks Tarun. I'll remove your name from these and we'll try to take care of them.

**Comment by moorepants** [comment]
Closing in favor of #224.

**Pull request closed without merging**
