### PR TITLE
Added new example for Anthropomorphic Arm.

### PR DESCRIPTION
**Pull request by Fernandohf**
New example for an Anthropomorphic Arm. The example has a notebook and a .py script. The Notebook is written in Portuguese as well as the comments in the script.

Example
-------

   - [x] There are no merge conflicts.
   - [x] A figure (preferrably SVG) has been added for the example.
   - [x] The required versions of all dependencie have been noted. (For
     notebooks, the [version information
     extension](https://github.com/jrjohansson/version_information) is helpful
     for this.)
   - [ ] A `run.py` file that executes the example is included.
   - [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by Fernandohf** [comment]
> The Notebook is written in Portuguese as well as the comments in the script.

 If necessary, I could translate the notebooks for English.

**Comment by moorepants** [comment]
> If necessary, I could translate the notebooks for English.

If you are willing to do that, I think that would be helpful as most of our current users likely rely on the English versions. I'm happy to include both and English and Portuguese version.

**Comment by moorepants** [comment]
It could be worth looking into this: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/nbTranslate/README.html There may be some options for supporting multiple languages more easily.

**Comment by Fernandohf** [comment]
Added the notebook with dual language with the [nbTranslate](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/nbTranslate/README.html) tool. However, if you don't have the extension installed the notebook shows all the cell with different languages together. Maybe files for each language would be less confuse?

**Comment by Fernandohf** [comment]
Added a a file for each language. I believe this is a least confusing approach.

**Comment by moorepants** [comment]
Thanks again for the submission!

**Pull request merged**
