### PR TITLE
Replace sympy.phyics.mechanics deprecated methods

### PR DESCRIPTION
**Pull request by oliverlee**
This commit resolves https://github.com/pydy/pydy/issues/296.

### CODE REVIEW

**Comment by moorepants** [comment]
Why does this pass when running on sympy 0.7.4.1? Aren't those attributes missing?

**Comment by oliverlee** [comment]
No: https://github.com/sympy/sympy/blob/d007af8e5cd4e7a7f4b3a0a603b7ced492c7a784/sympy/physics/mechanics/particle.py#L72

Some the tests use deprecated code so don't merge this yet.

**Comment by oliverlee** [comment]
This is done (well once it builds). I wasn't able to high deprecation warnings from running during tests though.

**Comment by moorepants** [comment]
Please update with master.

**Comment by moorepants** [comment]
Moving to #309.

**Pull request closed without merging**
