### PR TITLE
Updated the mass-spring-damper example to IPy4 and added version_information.

### PR DESCRIPTION
**Pull request by moorepants**
- [x] There are no merge conflicts.
- [ ] If there is a related issue, a reference to that issue is in the
  commit message.
- [ ] Unit tests have been added for the bug. (Please reference the issue #
  in the unit test.)
- [ ] The tests pass both locally (run `nosetests`) and on Travis CI.
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [ ] The bug fix is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
@pydy/pydy-developers Needs a quick review and merge.

**Comment by chrisdembia** [comment]
Needs to be updated.

**Comment by chrisdembia** [comment]
After updating the conflicts, this looks good to merge.

**Comment by moorepants** [comment]
It's weird that Github seems to require updates when they are unnecessary now.

**Pull request merged**
