### PR TITLE
Use new Theano and more clever calling to speed up Theano in this benchm...

### PR DESCRIPTION
**Pull request by nouiz**
...ark.

### CODE REVIEW

**Comment by lamblin** [comment]
Theano 0.7 has just been released.

**Comment by moorepants** [comment]
Thanks for the heads up. We'll get this change merged.

**Comment by oliverlee** [comment]
@nouiz
I've rebased your PR since there have been a number of changes since you submitted. Can you take a look when you have time?
https://github.com/oliverlee/pydy/tree/speedup-theano-generators

**Comment by nouiz** [comment]
Thanks for the rebase. I would change that a little.

This found a crash in Theano with the current master. I have a fix in this
PR:

https://github.com/Theano/Theano/pull/3507

I did a PR to your branch with a small change:

https://github.com/oliverlee/pydy/pull/1

**Comment by oliverlee** [comment]
This has been merged in another pull request: https://github.com/pydy/pydy/pull/267

**Pull request closed without merging**
