### PR TITLE
Changed to correct args for zeros().

### LINKED ISSUE #213: rollingdisc_nonminimal raises exception
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/chris/repos/pydy/examples/rollingdisc/rollingdisc_nonminimal.py in <module>()
    105 
    106 # Constraint coefficient matrix:  M_v * [u; ua] = 0
--> 107 M_v = zeros((3, 9))
    108 for i in range(3):
    109     for j, ui in enumerate(u + ua):

/Library/Python/2.7/site-packages/sympy/matrices/dense.pyc in zeros(r, c, cls)
   1227     if cls is None:
   1228         from .dense import Matrix as cls
-> 1229     return cls.zeros(r, c)
   1230 
   1231 

/Library/Python/2.7/site-packages/sympy/matrices/dense.pyc in zeros(cls, r, c)
    511         """Return an r x c matrix of zeros, square if c is omitted."""
    512         c = r if c is None else c
--> 513         r = as_int(r)
    514         c = as_int(c)
    515         return cls._new(r, c, [cls._sympify(0)]*r*c)

/Library/Python/2.7/site-packages/sympy/core/compatibility.pyc in as_int(n)
    387             raise TypeError
    388     except TypeError:
--> 389         raise ValueError('%s is not an integer' % n)
    390     return result
    391 

TypeError: not all arguments converted during string formatting
```

### PR DESCRIPTION
**Pull request by moorepants**
Fixes #213

Also updated the description of the problem.

- [x] There are no merge conflicts.
- [x] If there is a related issue, a reference to that issue is in the
  commit message.
- [ ] Unit tests have been added for the bug. (Please reference the issue #
  in the unit test.)
- [ ] The tests pass both locally (run `nosetests`) and on Travis CI.
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [ ] The bug fix is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [ ] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by moorepants** [comment]
@pydy/pydy-developers This needs a quick review and merge. Thanks.

**Comment by gilbertgede** [comment]
Everything seems in order. Does this change actually merit a unit test though (as in the checklist)?

**Comment by moorepants** [comment]
We are not unit testing examples, so that can be ignored. The default checklists work most of the time, but sometimes things need to be ignored. You can just note what was ignored in the comment.

**Comment by moorepants** [comment]
Merging, taking Gilbert's comment as a +1.

**Pull request merged**
