### PR TITLE
Tweaks the travis conda setup.

### LINKED ISSUE #160: Setup Travis testing with more testing options
I think we need these combinations:

1. Python 2.7 + lowest version of all deps we support (including optional deps).
2. Python 2.7 + lowest version of all deps we support (without optional deps).
3. Python 2.7 + SymPy master + latest version of deps.

We only have 1 right now.

Also, we could run the generation method benchmark in one of these.

### PR DESCRIPTION
**Pull request by moorepants**
Fixes #160 

@oliverlee Can you check over these changes and see if you are fine with them? It reintroduces testing on the range of deps we support.

- [x] There are no merge conflicts.
- [x] If there is a related issue, a reference to that issue is in the
  commit message.
- [x] Unit tests have been added for the bug. (Please reference the issue #
  in the unit test.)
- [ ] The tests pass both locally (run `nosetests`) and on Travis CI.
- [x] The code follows PEP8 guidelines. (use a linter, e.g.
  [pylint](http://www.pylint.org), to check your code)
- [x] The bug fix is documented in the [Release
  Notes](https://github.com/pydy/pydy#release-notes).
- [x] The code is backwards compatible. (All public methods/classes must
  follow deprecation cycles.)
- [x] All reviewer comments have been addressed.

### CODE REVIEW

**Comment by oliverlee** [comment]
Looks good assuming tests pass.

**Comment by oliverlee** [comment]
You need to change the versions

Hint: the following packages conflict with each other:
  - numpy 1.6.2*
  - theano 0.6*

**Comment by moorepants** [comment]
`conda install sympy=0.7.4` will install `0.7.4.1`. The single `=` in conda gets the lastest version in that series, in this can the latest version of `0.7.4`. Is that what you are referring to?

**Comment by oliverlee** [comment]
yes

**Comment by moorepants** [comment]
Ok, you can merge if you think this is good now.

**Pull request merged**
